language: java
jdk:
- oraclejdk8

before_install:
  - git clone -b travis `git config --get remote.origin.url` target/travis
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn clean deploy -P sonatype-oss-release -Dgpg.skip=true --settings target/travis/settings.xml || mvn clean verify --settings target/travis/settings.xml'

after_success:
  - mvn clean jacoco:prepare-agent test jacoco:report coveralls:jacoco

branches:
  only:
  - master

env:
  global:
  - secure: jwhbfbFNFeQpSLq8UkJfJX4HM3Q3axewkLdTAs/RicAfBKSoDZqVos9LAQcYeuN0iECDjos2hiG6CtiBncmK6D8FsjMdpNRXAip+oz+ChJqAq+Ch1HUejq2clKiSZb0abCMGOLPgmX9b0XbHf4qoyxUIJBpRyLjO0248OG9YifU=
  - secure: aWqtpf1d+NsArtPWYvGweoWeqjvUJnnp7FZ6BV7z6XJROW5aIYazEPOZ3C3Oa0TO5rK0pL9nItfMPE9GCbHxgpsiYuz8DTKvs+wTOmj3LprivAhk3PqYZN2+LfFEG9cRbxZTPBXDVRZ5jjGIcgxcLq0q6kv6Lka7aGrFtNozwMI=
